[package]
name = "tl-proto"
description = "A collection of traits for working with TL serialization/deserialization"
repository = "https://github.com/broxus/tl-proto"
version = "0.1.2"
edition = "2021"
include = ["src/**/*.rs", "README.md", "LICENSE"]
license-file = "./LICENSE"

[workspace]
members = ["proc", "test_suite"]

[dependencies]
digest = "0.9"
smallvec = { version = "1.7", features = ["union", "const_generics"] }
thiserror = "1.0"

tl-proto-proc = { version = "=0.1.1", path = "proc", optional = true }

[features]
derive = ["tl-proto-proc"]
