[package]
name = "tl-proto"
description = "A collection of traits for working with TL serialization/deserialization"
repository = "https://github.com/broxus/tl-proto"
version = "0.1.7"
edition = "2021"
include = ["src/**/*.rs", "README.md", "LICENSE"]
license-file = "./LICENSE"

[workspace]
members = ["proc", "test_suite"]

[dependencies]
bytes = { version = "1.1", optional = true }
digest = "0.10.1"
smallvec = { version = "1.7", features = ["union", "const_generics"] }
thiserror = "1.0"

tl-proto-proc = { version = "=0.1.7", path = "proc", optional = true }

[features]
default = ["derive", "bytes"]
derive = ["tl-proto-proc"]
