[package]
name = "tl-scheme"
description = "TL language grammar"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
repository = "https://github.com/broxus/tl-proto"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crc = "2"
pest = "2.1"
pest_derive = "2.1"
thiserror = "1.0"
serde_json = "1.0"
